[DEFAULT]
enabled_backends = synology

[synology]
backend_host = cinder-synology
volume_backend_name = synology
volume_driver = cinder.volume.drivers.synology.synology_iscsi.SynoISCSIDriver
target_protocol = iscsi
target_ip_address = 172.16.2.31
target_secondary_ip_addresses = 172.16.3.31
synology_admin_port = 5001
driver_use_ssl = True
synology_ssl_verify = False
driver_ssl_cert_verify = False
synology_username = <username>
synology_password = <password>
synology_pool_name = volume1
use_multipath_for_image_xfer = True

image_volume_cache_enabled = True
image_volume_cache_max_size_gb = 100
image_volume_cache_max_count = 20